name: Eleventy Build


on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies & build
        run: |
          npm install
          npx @11ty/eleventy
      - uses: actions/upload-pages-artifact@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - id: deployment
          uses: actions/deploy-pages@v2
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with: 
            deploy_key: $

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
